### ISSUE TITLE
Needs repository link in Cargo.toml

### ISSUE THREAD

**Issue by asomers** [fubarnetes/rctl#4]
Please add a repository tag in the Cargo.toml file so people can find the source from crates.io.  Also, a doc tag would be nice.  But you'll have to host the docs on github pages, since docs.rs doesn't do FreeBSD.  I find the cargo-release crate to be useful for uploading docs to github pages.

**Comment by fabianfreyer** [comment]
Ah, okay. Sure, I'll do that. Thanks for the pointer to `cargo-release` - It looks like it will be useful!
