### ISSUE TITLE
Released version on crates.io does not support FreeBSD 13

### ISSUE THREAD

**Issue by phyber** [fubarnetes/rctl#42]
Hi,

The current version of `rctl` on crates.io does not support FreeBSD 13. It would be great if a new version of the library could be released to fix this issue since we did add FreeBSD 13 support a while ago.

A new tagged version of libjail at the same time would be good as well.

Thanks, and sorry for prodding for a new version here.

**Comment by fabianfreyer** [comment]
v0.2.0 has been tagged and published. Sorry for the long wait!
